name: 'publish'
# on:
#     push:
#         tags: [v\d+\.\d+\.\d+]

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Build the Tauri apps"

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - target: aarch64-apple-darwin
                      platform: macos-latest
                    - target: x86_64-apple-darwin
                      platform: macos-latest
                    - target: x86_64-unknown-linux-gnu
                      platform: ubuntu-20.04
                    - target: x86_64-pc-windows-msvc
                      platform: windows-latest

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: Use PNPM
              uses: pnpm/action-setup@v2
              with:
                version: 8

            - name: Get version
              id: get_version
              uses: battila7/get-version-action@v2

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: './src-tauri -> target'

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libx11-dev libxdo-dev libxcb-shape0-dev libxcb-xfixes0-dev

            - name: install dependencies (mac only)
              if: matrix.platform == 'macos-latest'
              run: |
                  rustup target add aarch64-apple-darwin

            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                    ${{ runner.os }}-pnpm-store-

            - name: Install deps (with cache)
              run: pnpm install
    
            # - name: Build
            #   run: pnpm build

            # - name: Change Version
            #   env:
            #       VERSION: '${{ steps.get_version.outputs.version-without-v }}'
            #   run: make change-version

            - name: Build Tauri App
              uses: tauri-apps/tauri-action@dev
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
                  ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
                  APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
              with:
                  tagName: BOS_GATEWAY-v__VERSION__
                  releaseName: 'BOS GATEWAY v__VERSION__'
                  releaseBody: 'See the assets to download this version and install.'
                  releaseDraft: true
                  prerelease: false
                  args: --target ${{matrix.target}}